Updated dependencies and corrected checkstyle violations
open-feature/java-sdk pull request #1259
Opened 2024-12-20 16:11 UTC by itsfarhan

## Dependency Dashboard

- Updated dependencies and corrected checkstyle violations.

### Related Issues

Fixes #89 

### Notes

- I have updated versions of 2 dependencies.
- checkstyle v10.21.0
- mockito-core  v5.14.2

### How to test

- mvn test

![image](https://github.com/user-attachments/assets/3640bf67-15f0-494d-8131-20515ba3acd1)

2025-01-03 14:02 UTC, beeme1mr approved these changes

2025-01-03 14:55 UTC, aepfli commented on pom.xml
> +            <version>10.21.0</version>
Our build is running on java 8, check style 10+ require Java 11 - I think this will not work

2025-01-03 14:57 UTC, aepfli requested changes
Mockito and check style in this pull request version require Java 11 - we are building with Java 8. Hence this will not work.

As target version 1.8 is a requirement, we can think of updating our test build to a newer version, where we are executing those targets, but we are not able to merge this as is

2025-03-13 09:37 UTC, aepfli commented
with the migration to java 17 as our build java, all of this issues have been resolved and we have updated everything to the newest version, which are now updated via renovate accordingly.

Thank you for the pull request and your efforts

2025-03-13 09:37 UTC, closed without merging